'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CPDates.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _16498() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16498", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Actualiza la App.
        '''</summary>
        Friend ReadOnly Property actualiza() As String
            Get
                Return ResourceManager.GetString("actualiza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ah2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ah2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a By: DevMaxD.
        '''</summary>
        Friend ReadOnly Property by_max() As String
            Get
                Return ResourceManager.GetString("by_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hide the app.
        '''</summary>
        Friend ReadOnly Property hide() As String
            Get
                Return ResourceManager.GetString("hide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property ico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Manage your Dates.
        '''</summary>
        Friend ReadOnly Property manage_dates() As String
            Get
                Return ResourceManager.GetString("manage_dates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modifica tus Fechas.
        '''</summary>
        Friend ReadOnly Property maneja_datos() As String
            Get
                Return ResourceManager.GetString("maneja_datos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Date.
        '''</summary>
        Friend ReadOnly Property new_date() As String
            Get
                Return ResourceManager.GetString("new_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nexts Dates.
        '''</summary>
        Friend ReadOnly Property nexts_dates() As String
            Get
                Return ResourceManager.GetString("nexts_dates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property notif() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("notif", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Notificaciones.
        '''</summary>
        Friend ReadOnly Property notificaciones() As String
            Get
                Return ResourceManager.GetString("notificaciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Notifications.
        '''</summary>
        Friend ReadOnly Property notifications() As String
            Get
                Return ResourceManager.GetString("notifications", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nueva Fecha.
        '''</summary>
        Friend ReadOnly Property nueva_fecha() As String
            Get
                Return ResourceManager.GetString("nueva_fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Minimizar la App.
        '''</summary>
        Friend ReadOnly Property oculta() As String
            Get
                Return ResourceManager.GetString("oculta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Por: DevMaxD.
        '''</summary>
        Friend ReadOnly Property por_max() As String
            Get
                Return ResourceManager.GetString("por_max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Proximas Fechas.
        '''</summary>
        Friend ReadOnly Property prox_fechas() As String
            Get
                Return ResourceManager.GetString("prox_fechas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 2nd Plane.
        '''</summary>
        Friend ReadOnly Property second_plane() As String
            Get
                Return ResourceManager.GetString("second_plane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 2do Plano.
        '''</summary>
        Friend ReadOnly Property segundo_plano() As String
            Get
                Return ResourceManager.GetString("segundo_plano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Update the App.
        '''</summary>
        Friend ReadOnly Property update() As String
            Get
                Return ResourceManager.GetString("update", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
